<?php
namespace ERD\ImagineExtensionsBundle\Tests\ColorManagement;
use ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter;

/**
 * Test class for ColorConverter.
 * Generated by PHPUnit on 2012-06-17 at 15:04:51.
 */
class ColorConverterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ColorConverter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ColorConverter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::colorIndexToRGB
     * @todo Implement testColorIndexToRGB().
     */
    public function testColorIndexToRGB()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::RGBtoXYZ
     * @todo Implement testRGBtoXYZ().
     */
    public function testRGBtoXYZ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::XYZtoHunterLab
     * @todo Implement testXYZtoHunterLab().
     */
    public function testXYZtoHunterLab()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::XYZtoCIELAB
     * @todo Implement testXYZtoCIELAB().
     */
    public function testXYZtoCIELAB()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::colorIndexToHunterLab
     * @todo Implement testColorIndexToHunterLab().
     */
    public function testColorIndexToHunterLab()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::RGBToHunterLab
     * @todo Implement testRGBToHunterLab().
     */
    public function testRGBToHunterLab()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\ImagineExtensionsBundle\ColorManagement\ColorConverter::LABtoHue
     * @todo Implement testLABtoHue().
     */
    public function testLABtoHue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
